# Generated by Django 4.2.7 on 2023-11-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Full_name', models.CharField(max_length=100)),
                ('Image', models.FileField(upload_to='images/')),
                ('Email', models.EmailField(max_length=50)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Phone_Number', models.CharField(max_length=10, null=True)),
                ('Password', models.CharField(max_length=15, null=True)),
                ('Date_Time', models.DateTimeField(auto_now=True, null=True)),
                ('User_Status', models.CharField(default='pending', max_length=50, null=True)),
                ('Otp_Num', models.IntegerField(null=True)),
                ('Otp_Status', models.CharField(default='pending', max_length=60, null=True)),
                ('Last_Login_Time', models.TimeField(null=True)),
                ('Last_Login_Date', models.DateField(auto_now_add=True, null=True)),
                ('No_Of_Times_Login', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'user_detail',
            },
        ),
    ]
