# Generated by Django 4.2.7 on 2023-11-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_last_login_predict_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='Message',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
